//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaabiDocHF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dossier()
        {
            this.Mouvements = new HashSet<Mouvement>();
        }
    
        public int idDossier { get; set; }
        public int idBoite { get; set; }
        public int idProduit { get; set; }
        public int idUser { get; set; }
        public string codeDossier { get; set; }
        public string nomDossier { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public string dureeLegale { get; set; }
        public string dureeConv { get; set; }
    
        public virtual Boite Boite { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouvement> Mouvements { get; set; }
    }
}
