//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaabiDocHF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public int idMvnt { get; set; }
        public int idUser { get; set; }
        public int idDossier { get; set; }
        public int idMotif { get; set; }
        public Nullable<System.DateTime> dateRest { get; set; }
        public Nullable<System.DateTime> dateMvnt { get; set; }
        public string numCont { get; set; }
        public bool isValid { get; set; }
    
        public virtual Dossier Dossier { get; set; }
        public virtual Motif Motif { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
