//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaabiDocHF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Dossiers = new HashSet<Dossier>();
            this.Mouvements = new HashSet<Mouvement>();
            this.Roles = new HashSet<Role>();
        }
    
        public int idUser { get; set; }
        public int idBranche { get; set; }
        public string matriculeUser { get; set; }
        public string nomUser { get; set; }
        public string prenomUser { get; set; }
        public string adresseUser { get; set; }
        public string sexeUser { get; set; }
        public string cinUser { get; set; }
        public string mdpUser { get; set; }
        public Nullable<bool> rememberMeUser { get; set; }
        public Nullable<bool> isActiveUser { get; set; }
        public string emailUser { get; set; }
        public string FullUserName { get { return nomUser + " " + prenomUser; } }

        public virtual Branche Branche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dossier> Dossiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouvement> Mouvements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
